development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:859b6defc71469815cb4dcaa0c5ce711@pearlfish.redistogo.com:10386/
  channel_prefix: hnefatafl_production
  